# CircleCI configuration file
version: 2.1

# Use Orbs to simplify your config.
orbs:
  python: circleci/python@2.1.1
  docker: circleci/docker@2.2.0
  heroku: circleci/heroku@2.0.0

jobs:
  test-and-lint:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout # checkout source code
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python3 manage.py test
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
      - run:
          name: Run flake8
          command: flake8

workflows:
  build_test_deploy:
    jobs:
      - test-and-lint
