# CircleCI configuration file
version: 2.1

# Use Orbs to simplify your config.
orbs:
  python: circleci/python@2.1.1
  docker: circleci/docker@2.2.0
  heroku: circleci/heroku@2.0.0

jobs:

  # PIP & REQUIREMENTS
  pip-and-requirements:
    executor: python/default # use the default executor defined within the orb
    #docker:
    #  - image: cimg/python:3.10.2
    steps:
      - checkout # checkout source code
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Update pip
          command: pip install --upgrade pip
      - run:
          name: Install requirements
          command: pip install -r requirements.txt
  lint:
    executor: python/default # use the default executor defined within the orb
    #docker:
    #  - image: cimg/python:3.10.2
    steps:
      - checkout # checkout source code
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run flake8
          command: flake8
  test:
    executor: python/default # use the default executor defined within the orb
    #docker:
    #  - image: cimg/python:3.10.2
    steps:
      - checkout # checkout source code
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python3 manage.py test
      - store_test_results:
          path: test-results
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  # DOCKER
  build-push-docker-image:
    executor: python/default # use the default executor defined within the orb
    #docker:
    #  - image: cimg/python:3.10.2
    steps:
      - checkout # checkout source code
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $DOCKERHUB_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 .
      - run:
          name: Push Docker image
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1

  # HEROKU
  deploy-to-heroku:
    # executor: heroku/default
    docker:
      - image: $DOCKERHUB_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1
        auth:
            username: $DOCKERHUB_USERNAME
            password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      # - heroku/install
      - run:
          name: Deploy to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  build_test_deploy:
    jobs:
      - pip-and-requirements
      - lint
      - test
      - build-push-docker-image:
          requires:
            - lint
            - test
          filters:
            branches:
              only: master
      - deploy-to-heroku:
          requires:
            - build-push-docker-image
          filters:
            branches:
              only: master